name: protobuf_serializers
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  protobuf:
    path: '../protobuf'
  protobuf_encoding:
    path: '../protobuf_encoding'

dev_dependencies:
  test: ^1.16.0
